name: Call API
on:
  workflow_dispatch:
  schedule:
      - cron: '00 07 * * 1'
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      run:
        curl -XGET -H "Content-type: application/json" 'https://reportes-semanales.vercel.app/api/send_weekly_reports.js'
